---
- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  vars:
    ipaclient_domain: lab.lan
    ipaclient_realm: LAB.LAN
    ipaadmin_principal: admin
    ipaadmin_password: 'password!'
    ipaclient_use_otp: no
    smart_card_client: yes
    ipaserver_realm: LAB.LAN
  become: true

  roles:
  - role: ipaclient
    state: present
