---
- name: Playbook to configure IPA replicas
  hosts: ipareplicas
  become: true

  roles:
  - role: ipareplica
    state: present


- name: Setup smartcard auth
  hosts: ipareplicas
  become: true
  tasks:
    - name: Run SmartCard config
      shell: /root/SmartCard/config-client-for-smartcard.sh ca.crt
      ignore_errors: true

    - name: Update CA
      shell: ipa-certupdate
      
