- name: Update GDM configuration to hide previous logins
  blockinfile:
    path: /etc/dconf/db/local.d/00-login-screen
    block: |
      [org/gnome/login-screen]
      # Do not show the user list
      disable-user-list=true
  when: ansible_distribution_major_version == "8"

- name: Update dconf
  command: dconf update
  when: ansible_distribution_major_version == "8"

- name: Turn off gnome first setup windows
  lineinfile:
    line: 'X-GNOME-Autostart-enabled=false'
    path: /etc/xdg/autostart/gnome-initial-setup-first-login.desktop 

