---
- name: install packages dependent on plays
  yum:
    name:
      - opensc
      - dconf
      - expect
    state: present

- name: start and enable services
  service: 
    name: pcscd
    state: started
    enabled: yes

### Added in to support password complexity, thank you to Dean for helping me find this issue ###

- name: Ensure admin keytab is valid
  shell: |
    spawn kinit admin@{{ ipaserver_realm }}

    expect "Password for admin@{{ ipa_realm }}:"
    send "{{ ipaadmin_password }}\n"
  args:
    executable: /usr/bin/expect

- name: update IPA CA cert database
  command: /usr/sbin/ipa-certupdate

- name: Copy Root and Sub chain to client
  copy:
    src: "{{ item }}"
    dest: "/root/"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "roles/ipaserver/files/{{ current_cert_version }}/*.pem"

- name: Import CA trust chain
  copy:
    src: /root/DoD_CAs.pem
    dest: /etc/pki/ca-trust/source/anchors/DoD_CAs.pem
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Run CA system update
  shell: update-ca-trust

- name: Clean up certificates
  file:
    path: "/root/{{ item }}"
    state: absent
  with_fileglob:
    - "*.pem"

- name: modify krb5_auth_timeout
  lineinfile:
    regexp: '^krb5_auth_timeout*'
    insertafter: '^\[domain*'
    line: 'krb5_auth_timeout = 60'
    path: /etc/sssd/sssd.conf


- name: modify p11_child_timeout
  lineinfile:
    regexp: '^p11_child_timeout*'
    insertafter: '^\[pam\]'
    line: 'p11_child_timeout = 60'
    path: /etc/sssd/sssd.conf

- name: configure ocsp
  lineinfile:
    regexp: '^certificate_verification*'
    insertafter: '^\[sssd\]'
    line: 'certificate_verification = no_ocsp'
    #line: 'certificate_verification = iocsp_default_responder={{ ocsp_proxy }},ocsp_default_responder_signing_cert={{ ocsp_cert_nick }}'
    path: /etc/sssd/sssd.conf

- name: configure sssd to use short usernames
  lineinfile:
    regexp: '^full_name_format*'
    insertafter: '^\[sssd\]'
    line: 'full_name_format = %1$s'
    path: /etc/sssd/sssd.conf

- name: configure alias for pkinit
  lineinfile:
     regexp: '^alias pkinit*'
     line: alias pkinit="kinit -X X509_user_identity='PKCS11:opensc-pkcs11.so'"
     path: /etc/bashrc

- name: restart sssd
  systemd:
    name: sssd
    state: restarted

- name: Copy krb5 template
  template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy current CA for smart card auth run
  copy:
    src: /etc/ipa/ca.crt
    dest: /root/ca.crt
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Copy script from role
  copy:
    src: files/config-client-for-smart-card-auth.sh
    dest: /root/config-client-for-smart-card-auth.sh
    owner: root
    group: root
    mode: '0755'

- name: Run config client for Smart Card script
  shell: ./config-client-for-smart-card-auth.sh /etc/ipa/ca.crt
  args:
    chdir: /root
  register: sc_script_debug
  ignore_errors: True
